simulation_metadata:
  num_episodes: 3
  num_steps_per_episode: 20
  num_substeps_per_step: 1
  h: 72
  w: 72
  n_channels: 16
  batch_size: 8
  device: cpu
  hidden_size: 128
  fire_rate: 0.5
  angle: 0.0
  learning_params:
    lr: 0.002
    betas:
    - 0.5
    - 0.5
    lr_gamma: 0.9999
    model_path: saved_model.pth
state:
  environment: {}
  agents:
    automata:
      number: 5184
      properties:
        cell_state:
          name: cell_state
          shape:
          - 16
          initialization_function:
            generator: nca_initialize_state
            arguments:
              n_channels:
                name: n_channels
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 16
              batch_size:
                name: batch_size
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 8
              device:
                name: device
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: str
                value: cpu
          learnable: true
          dtype: float
  objects: {}
  network:
    agent_agent:
      evolution_network:
        type: grid_network
        arguments:
          shape:
          - 72
          - 72
substeps:
  '0':
    name: Evolution
    active_agents:
    - automata
    observation:
      automata: null
    policy:
      automata: null
    transition:
      generator: NCAEvolve
      input_variables:
        cell_state: agents/automata/cell_state
      output_variables:
      - cell_state
      arguments: null
