simulation_metadata:
    num_episodes: 2
    num_steps_per_episode: 20
    num_substeps_per_step: 3
    device: "cpu"
    num_citizens: 100

state:
  environment: null
  agents:
    citizens:
      number: ${simulation_metadata.num_citizens}
      properties:
        id:
          name: "Agent Id"
          shape:
            - ${state.agents.citizens.number}
            - 1
          learnable: False
          initialization_function:
              generator: "read_from_file"
              arguments:
                  file_path:
                    name: "Filepath for agent id"
                    learnable: False
                    shape: null
                    initialization_function: null
                    value: ${simulation_metadata.agent_id_file}                               
          dtype: "int"

        age:
        household_id:
        race: 
        occupation_status:
        assets:
        liabilities:

    households:
      number: ${simulation_metadata.num_households}
      properties:
        id: 
          name: "Household Id"
          shape:
            - ${state.agents.households.number}
            - 1
          learnable: False
          initialization_function:
            generator: "read_from_file"
            arguments:
              file_path:
                name: "Filepath for household id"
                learnable: False
                shape: null
                initialization_function: null
                value: ${simulation_metadata.household_id_file}
          dtype: "int"

        size:
          name: "Household sizes"
          shape:
            - ${state.agents.households.number}
            - 1
          learnable: False
          initialization_function:
            generator: "read_from_file"
            arguments:
              file_path:
                name: "Filepath for household size"
                learnable: False
                shape: null
                initialization_function: null
                value: ${simulation_metadata.household_size_file}
          dtype: "int"
        
        assets:
          name: "Household assets"
          shape:
            - ${state.agents.households.number}
            - 1
          learnable: False
          initialization_function:
            generator: "read_from_file"
            arguments:
              name: "Filepath for household assets"
              learnable: False
              shape: null
              initialization_function: null
              value: ${simulation_metadata.household_assets_file}
          dtype: "int"

        liabilities:
          name: "Household liabilities"
          shape:
            - ${state.agents.households.number}
            - 1
          learnable: False
          initialization_function:
            generator: "read_from_file"
            arguments:
              name: "Filepath for household liabilities"
              learnable: False
              shape: null
              initialization_function: null
              value: ${simulation_metadata.household_liabilities_file}
          dtype: "int"

  objects:
    metadata:
      num_stimulus: 2
    StimulusPayment:
      number: 2
      properties:
        amount:
          name: "Infrequent amounts for of Stimulus Payments"
          shape:
            - ${state.objects.metadata.num_steps}
            - 1
          learnable: False
          initialization_function:
            generator: "store_sparse"
            arguments:
              name: "Sparse tensor of stimulus payments"
              arg
          value: 
            - 600
            - 300
          dtype: "int"

  network: null

substeps:
  "0":
    name: "StimulusPayment"
    description: "Stimulus payment"
    active_agents:
        - "citizens"
    observation:
      citizens:
        time_for_next_payment:  
    policy:
      citizens:

    transition: