simulation_metadata:
    num_episodes: 2
    num_steps_per_episode: 7
    num_substeps_per_step: 1
    device: "cpu"
    execution_mode: "llm" # or llm
    num_agents: 37518
    learning_params:
        lr: 0.002
        betas:
            - 0.5
            - 0.5
        lr_gamma: 0.9999
        model_path: saved_model.pth
    work_prompt: "Do you want to work?"
    consumption_prompt: "Do you want to {daily limit} consume?"
    natural_unemployment_rate: 0.05
    natural_interest_rate: 0.05
    target_inflation_rate: 0.02
    maximum_rate_of_change_of_wage: 0.05
    maximum_rate_of_change_of_price: 0.05
    inflation_adaptation_coefficient: 0.05
    unemployment_adaptation_coefficient: 0.05
    universal_productivity: 1.0
    hourly_wage: 1.0
    hours_worked: 168.0
    tax_brackets : [0, 50, 100, 500]
    tax_rates : [0.1, 0.2, 0.3,0.35]
    population_dir: '/u/ayushc/projects/GradABM/MacroEcon'   
    mapping_path: "/u/ayushc/projects/GradABM/MacroEcon/data/step2/process/mapping.json"
    OPENAI_API_KEY: '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'
state:
    environment:
        P: 
            name: "Price of Essential Goods"
            learnable: True
            shape:
                - 1
            initialization_function: null
            value: 12.0
            dtype: float
        R:
            name: "Interest Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        P_i: 
            name: "Inflation Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        U: 
            name: "Unemployment Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        G: 
            name: "Goods Inventory"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 0.0
            dtype: float
        D: 
            name: "Demand"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 0.0
            dtype: float
        Avg_P: 
            name: "Average Price"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 0.0
            dtype: float
        Month_Counter: 
            name: "Total months"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        Im: 
            name: "Imbalance"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 0.0
            dtype: float
        Cumm_P: 
            name: "Cummulative Price of Essential Goods"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 0.0
            dtype: float          
    agents:
        consumers:
            number: ${simulation_metadata.num_agents}
            properties:
                ID: 
                    name: ID
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number} # to verify this. number of networks
                        - 1
                    initialization_function:
                        generator: "initialize_id"
                        arguments:
                            pop_size:
                                name: "population size"
                                learnable: false
                                shape:
                                    - 1
                                initialization_function: null
                                value: ${state.agents.consumers.number}
                    dtype: "float"
                Gender:
                    name: Gender
                    learnable: False
                    shape:
                        - ${state.agents.consumers.number} # to verify this. number of networks
                        - 1
                    initialization_function:
                        generator: "load_population_attribute"
                        arguments:
                            file_path:
                                name: "Filepath for age group stage"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: ${simulation_metadata.population_dir}/gender.pickle
                            attribute:
                                name: "Age"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: 'gender'             
                    dtype: "float"
                
                Age:
                    name: Age
                    learnable: False
                    shape:
                        - ${state.agents.consumers.number} # to verify this. number of networks
                        - 1
                    initialization_function:
                        generator: "load_population_attribute"
                        arguments:
                            file_path:
                                name: "Filepath for age group stage"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: ${simulation_metadata.population_dir}/age.pickle
                            attribute:
                                name: "Age"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: 'age'         
                    dtype: "float"

                Ethnicity:
                    name: Ethnicity
                    learnable: False
                    shape:
                        - ${state.agents.consumers.number} # to verify this. number of networks
                        - 1
                    initialization_function:
                        generator: "load_population_attribute"
                        arguments:
                            file_path:
                                name: "Filepath for age group stage"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: ${simulation_metadata.population_dir}/ethnicity.pickle
                            attribute:
                                name: "Ethnicity"
                                learnable: False
                                shape: null
                                initialization_function: null     
                                value: 'ethnicity'     
                    dtype: "float"
                
                Area: 
                    name: Area
                    learnable: False
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function:
                        generator: "load_population_attribute"
                        arguments:
                            file_path:
                                name: "Filepath for age group stage"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: ${simulation_metadata.population_dir}/area.pickle 
                            attribute:
                                name: "Area"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: 'area'     
                    dtype: "float"

                Whether_to_Work:
                    name: Whether to Work
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                    
                Conpsumption_Propensity:
                    name: Conpsumption_Propensity
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                    
                Savings:
                    name: Savings
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                    
                Work_Propensity:
                    name: Work_Propensity
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                    
                Post_Tax_Income:
                    name: Post_Tax_Income
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                    
                Monthly_Income:
                    name: Monthly_Income
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                    
                Monthly_Consumption:
                    name: Monthly_Consumption
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                    
    objects:
        metadata:
            num_jobs: 2
        JobA:
            number: 1
            properties:
                wage:
                    name: "Wage"
                    shape:
                        - ${state.objects.JobA.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float" 
                            
                productivity:
                    name: "Productivity"
                    shape:
                        - ${state.objects.JobA.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float"

        JobB:
            number: 1
            properties:
                wage:
                    name: "Wage"
                    shape:
                        - ${state.objects.JobB.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float"
                            
                productivity:
                    name: "Productivity"
                    shape:
                        - ${state.objects.JobB.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float"
               
    network:
        agent_agent:
            opinion_network:
                type: grid
                arguments:
                    shape:
                        - 80
                        - 80
        agent_object: null
        object_object: null

substeps:
    # Agents earn (employment + interest income), Agent spend (consumption + taxation), Market evolves (macro-rates, goods)
    "0":
        name: "Agents Earn"
        description: "Agents earn from hourly employment and interest on old assets"
        active_agents:
            - consumers
        observation:
            consumers: null
        policy:
            consumers:
                get_work_consumption_decision:
                    generator: "WorkConsumptionPropensity"
                    arguments: null
                    input_variables:
                        Age : 'agents/consumers/Age'
                        Gender : 'agents/consumers/Gender'
                    output_variables:
                        - Whether_to_Work
                        - Work_Propensity
                        - Consumption_Propensity
                        
        transition:
            update_assets:
                generator: "UpdateAssets"
                arguments: null
                input_variables:
                    assets: 'agents/consumers/assets'
                    hourly_wage: 'objects/JobA/wage'
                    interest_rate: 'environment/R'
                output_variables:
                    - assets
            
            write_to_state:
                generator: "WriteToState"
                arguments: null
                input_variables:
                    Consumption_Propensity: "agents/consumers/ConsumptionPropensity"
                output_variables:
                    - Consumption_Propensity
                    
    "1":
        name: "Agents Spend"
        description: "Agents spend assets on consumption and taxation"
        active_agents:
            - consumers
        observation:
            consumers: null
        policy:
            consumers: null
        transition:
            update_assets_and_good:
                generator: "UpdateAssetsGoods"
                arguments: null
                input_variables:
                output_variables:
                    - assets
                    - goods_inventory
            
    "2":
        name: "Market Quantities"
        description: "Government sets macro parameters and updates them based on agent behavior"
        active_agents:
            - consumers
        observation:
            consumers: null
        policy:
            consumers: null
        transition:
            update_macro_rates:
                generator: "UpdateMacroRates"
                arguments: null
                input_variables:
                    
                output_variables:
                    - Hourly_Wage
                    - Inflation_Rate
                    - Interest_Rate
                    - Unemployment_Rate

#         transition:
#             UpdateMacroeconomics:
#                 generator: UpdateMacroeconomics
#                 arguments: null
#                 input_variables:
#                     Num_Agents: 'agents/consumers/number'
#                     Month_Counter: 'environment/Month_Counter'
#                     Savings: 'agents/consumers/Savings'
#                     Goods_Inventory: 'environment/G'
#                     Demand_of_Goods: 'environment/D'
#                     Imbalance: 'environment/Im'
#                     Hourly_Wage: 'objects/JobA/wage'
#                     Price_of_Goods: 'environment/P'
#                     Interest_Rate: 'environment/R'
#                     Average_Price_of_goods: 'environment/Avg_P'
#                     Consumption_Propensity: 'agents/consumers/Conpsumption_Propensity'
#                     Inflation_Rate: 'environment/P_i'
#                     Unemployment_Rate: 'environment/U'
#                     Cummulative_Price_of_Goods: 'environment/Cumm_P'

#                 output_variables:
#                     - Goods_Inventory
#                     - Demand_of_Goods
#                     - Imbalance
#                     - Hourly_Wage
#                     - Price_of_Goods
#                     - Cummulative_Price_of_Goods
#                     - Inflation_Rate
                    
#             UpdateFinancialMarket:
#                 generator: UpdateFinancialMarket
#                 arguments: null
#                 input_variables: 
#                     Work_Propensity: 'agents/consumers/Work_Propensity'
#                     Monthly_Income: 'agents/consumers/Monthly_Income'
#                     Interest_Rate: 'environment/R'
#                     Inflation_Rate: 'environment/P_i'
#                     Unemployment_Rate: 'environment/U'
#                     Month_Counter: 'environment/Month_Counter'
#                 output_variables:
#                     - Interest_Rate
#                     - Unemployment_Rate