state:
  environment:
    generate_work_profile:
      prompt: "Create 10 work profiles"
    calculate_taxation_coeff:
      prompt: "Calculate the taxation coefficient {current_taxation_coeff}"
    calculate_inflation_coeff:
      prompt: "Calculate the inflation coefficient {current_inflation_coeff}"
  
  agents:
    substeps:
      "0": 
        observation:
              prompt: "What is the current state of the economy?"
        action:
              prompt: "What is the work propensity?"
        transition:
              prompt: "What is the miscelleeous expenses?"