simulation_metadata:
  num_episodes: 10
  num_steps_per_episode: 25
  num_substeps_per_step: 1
  device: cpu
  num_agents: 6400
  num_products: 2
state:
  environment: {}
  agents:
    consumers:
      number: 6400
      properties:
        F_t:
          name: Follower Tendency
          shape:
          - 6400
          - 1
          initialization_function:
            generator: random_normal
            arguments:
              mu:
                name: ft_mean
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: float
                value: 0.5
              sigma:
                name: ft_sigma
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: float
                value: 0.67
          learnable: true
          dtype: float
        Purchased_before:
          name: Purhcased before
          shape:
          - 6400
          - null
          initialization_function: null
          learnable: false
          dtype: float
          value: 0.5
        Q_exp:
          name: Quality Experienced
          shape:
          - 6400
          - null
          initialization_function:
            generator: random_normal_col_by_col
            arguments:
              mu_0:
                name: Q_exp_mu_0
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: float
                value: 0.5
              mu_1:
                name: Q_exp_mu_1
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: float
                value: 0.5
              sigma_0:
                name: Q_exp_sigma_0
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: float
                value: 0.2
              sigma_1:
                name: Q_exp_sigma_1
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: float
                value: 0.2
          learnable: false
          dtype: float
        Q_des:
          name: Quality desired
          shape:
          - 6400
          - 1
          initialization_function: null
          learnable: false
          dtype: float
          value: 0.5
    marketers:
      number: 2
      properties: {}
  objects:
    ProductA:
      number: 1
      properties:
        cost:
          name: ProductA cost
          shape:
          - 1
          - 1
          initialization_function: false
          learnable: false
          dtype: float
        quality:
          name: ProductA quality
          shape:
          - 1
          - 1
          initialization_function: false
          learnable: false
          dtype: float
    ProductB:
      number: 1
      properties:
        cost:
          name: ProductB cost
          shape:
          - 1
          - 1
          initialization_function: false
          learnable: false
          dtype: float
        quality:
          name: ProductB quality
          shape:
          - 1
          - 1
          initialization_function: false
          learnable: false
          dtype: float
  network:
    agent_agent:
      opinion_network:
        type: grid_network
        arguments:
          shape:
          - 80
          - 80
substeps:
  '0':
    name: New Purchase
    active_agents:
    - consumers
    observation:
      generator: GetNeighborsSumReduced
      input_variables:
        F_t: agents/consumers/F_t
        Q_des: num_agents/consumers/Q_des
        Q_exp: agents/consumers/Q_exp
        adjancency_matrix: network/agent_agent/opinion_network/adjacency_matrix
        query_feature: agents/consumers/purchased_before
      output_variables:
      - N_p
      arguments:
        neighborhood:
          name: Neighborhood Scope
          shape:
          - 1
          initialization_function: null
          learnable: false
          dtype: int
          value: 1
    policy:
      generator: PurchaseProduct
      input_variables:
        N_i: N_i
        N_p: N_p
        F_t: F_t
        Q_des: Q_des
        Q_exp: Q_exp
      output_variables:
      - purchase_action
      arguments: null
    transition:
      generator: NewPurchasedBefore
      input_variables:
        Q_exp: agents/consumers/Q_exp
        Purchase_before: agents/consumers/Purchased_before
      output_variables:
      - Purchase_before
      arguments: null
