simulation_metadata:
    num_episodes: 1
    num_steps_per_episode: 10
    num_substeps_per_step: 1
    device: cpu
    learning_params:
        lr: 0.002
        betas:
            - 0.5
            - 0.5
        lr_gamma: 0.9999
        model_path: saved_model.pth
    work_prompt: "Do you want to work?"
    consumption_prompt: "Do you want to {daily limit} consume?"
state:
    environment:
        P: 
            name: "Price of Essential Goods"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        R:
            name: "Interest Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        P_i: 
            name: "Inflation Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        U: 
            name: "Unemployment Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        R_n: 
            name: "Natural Interest Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        P_i_T: 
            name: "Inflation Target"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
        U_n: 
            name: "Natural Unemployment Rate"
            learnable: false
            shape:
                - 1
            initialization_function: null
            value: 1.0
            dtype: float
    agents:
        consumers:
            number: 6400
            properties:
                Whether_to_Work:
                    name: Whether to Work
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function:
                        generator: random_normal
                        arguments:
                            mu:
                                name: F_t mean
                                learnable: false
                                shape:
                                    - 1
                                initialization_function: null
                                value: 0.5
                                dtype: float
                            sigma:
                                name: F_t sigma
                                learnable: false
                                shape:
                                    - 1
                                initialization_function: null
                                value: 0.67
                                dtype: float
                    dtype: float
                Conpsumption_Propensity:
                    name: Conpsumption_Propensity
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.5
                    dtype: float
                Savings:
                    name: Savings
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                Work_Propensity:
                    name: Work_Propensity
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                Post_Tax_Income:
                    name: Post_Tax_Income
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
                Monthly_Income:
                    name: Monthly_Income
                    learnable: false
                    shape:
                        - ${state.agents.consumers.number}
                        - 1
                    initialization_function: null
                    value: 0.0
                    dtype: float
    objects:
        metadata:
            num_jobs: 2
        JobA:
            number: 1
            properties:
                wage:
                    name: "Wage"
                    shape:
                        - ${state.objects.JobA.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float" 
                            
                productivity:
                    name: "Productivity"
                    shape:
                        - ${state.objects.JobA.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float"

        JobB:
            number: 1
            properties:
                wage:
                    name: "Wage"
                    shape:
                        - ${state.objects.JobB.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float"
                            
                productivity:
                    name: "Productivity"
                    shape:
                        - ${state.objects.JobB.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: 1.0
                    dtype: "float"
    network:
        agent_agent:
            opinion_network:
                type: grid
                arguments:
                    shape:
                        - 80
                        - 80
        agent_object: null
        object_object: null
substeps:
    "0":
        name: New Month
        description: A new month is started
        active_agents:
            - consumers
        observation:
        policy:
            CalulateWorkPropensity:
                generator: CalculateWorkPropensity
                arguments: null
                input_variables: null
                output_variables:
                    - Work_Propensity
                    - Whether_to_Work
            CalculateConsumptionPropensity:
                generator: CalculateConsumptionPropensity
                arguments: null
                input_variables: null
                output_variables:
                    - Conpsumption_Propensity
        transition:
            UpdateSavings:
                generator: UpdateSavings
                arguments: null
                input_variables: null
                output_variables:
                    - Savings
            UpdateMacroEconomicVariables:
                generator: UpdateMacroEconomicVariables
                arguments: null
                input_variables: null
                output_variables:
                    - P
                    - R
                    - P_i
                    - U

        reward: null
