simulation_metadata:
  num_episodes: 10
  num_steps_per_episode: 30
  num_substeps_per_step: 2
  device: cpu
  num_citizens: 70916
  agent_id_file: data/25011_id.csv
  age_group_file: data/25011_age.csv
  disease_stage_file: data/25011_stage.csv
  infection_network_file: data/25011_network.csv
  SUSCEPTIBLE_VAR: 0
  EXPOSED_VAR: 1
  INFECTED_VAR: 2
  RECOVERED_VAR: 3
  MORTALITY_VAR: 4
state:
  environment: {}
  agents: {}
  objects: {}
  network: {}
substeps: {}
