simulation_metadata:
    num_episodes: 1
    num_steps_per_episode: 4
    num_substeps_per_step: 4
    device: "cpu"
    num_agents: 37518
    initial_infection_ratio: 0.04
    population_dir: "/u/ayushc/projects/GradABM/MacroEcon/simulator_data/census_populations/NYC/simulation_input"
    mapping_path: ${simulation_metadata.population_dir}/population_mapping.json
    age_group_file: ${simulation_metadata.population_dir}/age.pickle
    infection_network_file: ${simulation_metadata.population_dir}/mobility_networks/0.csv
    disease_stage_file: "nyc_disease_stages.csv"
    SUSCEPTIBLE_VAR: 0
    EXPOSED_VAR: 1
    INFECTED_VAR: 2
    RECOVERED_VAR: 3
    MORTALITY_VAR: 4
    EXPOSED_TO_INFECTED_TIME: 3
    INFECTED_TO_RECOVERED_TIME: 5
    INFINITY_TIME: 100
    quarantine_days: 12
    test_result_delay_days: 3
    test_ineligible_days: 2
    
state:
    environment:
        R:
            name: "R"
            learnable: True
            shape:
                - 1
            initialization_function: null
            value: 5.12
            dtype: "float"
        
        SFSusceptibility:
            name: "Susceptibility by Age Group"
            learnable: False
            shape:
                - 9
            initialization_function: null
            value: 
                - 0.35
                - 0.69
                - 1.03
                - 1.03
                - 1.03
                - 1.03
                - 1.27
                - 1.52
                - 1.52
            dtype: "float"
            
        SFInfector:
            name: "Infectiousness of Infector"
            learnable: False
            shape:
                - 5
            initialization_function: null
            value:
                - 0.0
                - 0.33
                - 0.72
                - 0.0
                - 0.0
            dtype: "float"
        
        mortality_rate:
            name: "Mortality Rate"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 0.2
            dtype: "float"
        
        exposed_to_infected_time:
            name: "Time from Exposed to Infected"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 3
            dtype: "float"
        
        infected_to_recovered_time:
            name: "Infected to Recovered time"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 5
            dtype: "float"
        
        quarantine_start_prob:
            name: "Probability of complying to a quarantine mandate"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 0.7
            dtype: "float"
        
        quarantine_break_prob:
            name: "Probability of breaking a quarantine mandate prior to recovery"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 0.1
            dtype: "float"
            
        test_true_positive_prob:
            name: "Probability of true positive test result"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 0.8
            dtype: "float"
            
        test_false_positive_prob:
            name: "Probability of false positive test result"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 0.3
            dtype: "float"
        
        test_compliance_prob:
            name: "Probability of complying to test recommendation"
            learnable: False
            shape:
                - 1
            initialization_function: null
            value: 0.95
            dtype: "float"

        lam_gamma_integrals:
            name: "Lam Gamma Integrals"
            learnable: False
            shape:
                - 10
            initialization_function:
                generator: "get_lam_gamma_integrals"
                arguments:
                    scale: 
                        name: "Lam Gamma Scale"
                        learnable: False
                        shape:
                            - 1
                        initialization_function: null
                        value: 5.5
                        dtype: "float"
                    rate:
                        name: "Lam Gamma Rate"
                        learnable: False
                        shape:
                            - 1
                        initialization_function: null
                        value: 2.4
                        dtype: "float"
                    t:
                        name: "Num Steps"
                        learnable: False
                        shape:
                            - 1
                        initialization_function: null
                        value: ${simulation_metadata.num_steps_per_episode}
                        dtype: "int"
            dtype: "float"
            
        mean_interactions:
            name: "Mean agent interactions across networks"
            learnable: False
            shape:
                - ${simulation_metadata.num_agents} # number of agents
                - 1 # number of networks
            initialization_function:
                generator: "get_mean_agent_interactions"
                arguments:
                    file_path:
                        name: "Filepath for age group stage"
                        learnable: False
                        shape: null
                        initialization_function: null
                        value: ${simulation_metadata.age_group_file}           
            dtype: "int"
            
    agents:
        citizens:
            number: ${simulation_metadata.num_agents}
            properties:
                id:
                  dtype: "float"
                  initialization_function:
                    arguments:
                      pop_size:
                        initialization_function: null
                        learnable: false
                        name: "population size"
                        shape:
                        - 1
                        value: ${simulation_metadata.num_agents}
                    generator: initialize_id
                  learnable: false
                  name: "ID"
                  shape:
                  - ${state.agents.citizens.number}
                  - 1
            
                age:
                    name: "Age"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function:
                        generator: load_population_attribute
                        arguments:
                            attribute:
                                initialization_function: null
                                learnable: false
                                name: Age
                                shape: null
                                value: age
                            file_path:
                                initialization_function: null
                                learnable: false
                                name: Filepath for age group stage
                                shape: null
                                value: ${simulation_metadata.age_group_file}
                    dtype: "int"
                    
                disease_stage:
                    name: "Disease Stage"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function:
                        generator: "read_from_file"
                        arguments:
                            file_path:
                                name: "Disease Stage File"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: ${simulation_metadata.disease_stage_file}
#                     initialization_function:
#                         generator: "initialize_infections"
#                         arguments:
#                             num_agents:
#                                 name: "Number of agents"
#                                 learnable: False
#                                 shape: null
#                                 initialization_function: null
#                                 value: ${simulation_metadata.num_agents}
#                             initial_infected_ratio:
#                                 name: "Initial infection ratio"
#                                 learnable: False
#                                 shape: null
#                                 initialization_function: null
#                                 value: ${simulation_metadata.initial_infection_ratio}
                    dtype: "int"
                
                infected_time:
                    name: "Last Infected timestep"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function:
                        generator: "get_infected_time"
                        arguments:
                            file_path:
                                name: "Filepath for initial disease stages"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: ${simulation_metadata.disease_stage_file}
                            num_steps:
                                name: "Num steps per episode"
                                learnable: False
                                shape:
                                    - 1
                                initialization_function: null
                                value: ${simulation_metadata.num_steps_per_episode}
                    dtype: "int"
                    
                next_stage_time:
                    name: "Timestep for next transition"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function:
                        generator: "get_next_stage_time"
                        arguments:
                            file_path:
                                name: "Filepath for initial disease stages"
                                learnable: False
                                shape: null
                                initialization_function: null
                                value: ${simulation_metadata.disease_stage_file}
                            num_steps:
                                name: "Num steps per episode"
                                learnable: False
                                shape:
                                    - 1
                                initialization_function: null
                                value: ${simulation_metadata.num_steps_per_episode}
                    value: 0
                    dtype: "int"
                    
                is_quarantined:
                    name: "Quarantine status for a citizen"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: False
                    dtype: "bool"
                    
                quarantine_start_date:
                    name: "Start date for last quarantine of agent"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: ${simulation_metadata.INFINITY_TIME}
                    dtype: "int"
                    
                awaiting_test_result:
                    name: "agent is awaiting test result currently"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: False
                    dtype: "bool"
                
                test_result_date:
                    name: "Date when agent receives test result"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: ${simulation_metadata.INFINITY_TIME}
                    dtype: "int"
                
                test_re_eligble_date:
                    name: "Date when agent becomes eligible for taking a test again"
                    shape:
                        - ${state.agents.citizens.number}
                        - 1
                    learnable: False
                    initialization_function: null
                    value: ${simulation_metadata.INFINITY_TIME}
                    dtype: "int"
                
    objects: null
    
    network:
        agent_agent:
            infection_network:
                type: "network_from_file"
                arguments:
                    file_path: ${simulation_metadata.infection_network_file}

substeps:
    "0":
        name: "Transmission"
        description: "Transmission of new infections"
        active_agents:
            - "citizens"
        observation:
            citizens: null
        policy:
            citizens: null
        transition:
            new_transmission:
                generator: "NewTransmission"
                arguments: null
                input_variables:
                    R: 'environment/R'
                    SFSusceptibility: 'environment/SFSusceptibility'
                    SFInfector: 'environment/SFInfector'
                    lam_gamma_integrals: 'environment/lam_gamma_integrals'
                    mean_interactions: 'environment/mean_interactions'
                    age: 'agents/citizens/age'
                    disease_stage: 'agents/citizens/disease_stage'
                    next_stage_time: 'agents/citizens/next_stage_time'
                    infected_time: 'agents/citizens/infected_time'
                    exposed_to_infected_time: 'environment/exposed_to_infected_time'
                    adjacency_matrix: 'network/agent_agent/infection_network/adjacency_matrix'
                output_variables:
                    - disease_stage
                    - next_stage_time
                    - infected_time
        reward: null
        
    "1":
        name: "Disease Progression"
        description: "Evolution of previously infected agents"
        active_agents:
            - "citizens"
        observation:
            citizens: null
        policy:
            citizens: null
        transition:
            seirm_progression:
                generator: "SEIRMProgression"
                arguments: null
                input_variables:
                    disease_stage: 'agents/citizens/disease_stage'
                    next_stage_time: 'agents/citizens/next_stage_time'
                    exposed_to_infected_time: 'environment/exposed_to_infected_time'
                    infected_to_recovered_time: 'environment/infected_to_recovered_time'
                output_variables:
                    - disease_stage
                    - next_stage_time
        reward: null
        
    "2":
        name: "Quarantine"
        description: "Quarantining of infected agents"
        active_agents:
            - "citizens"
        observation:
            citizens:
                get_from_state:
                    generator: "GetFromState"
                    arguments: null
                    input_variables:
                        quarantine_start_prob: "environment/quarantine_start_prob"
                        quarantine_break_prob: "environment/quarantine_break_prob"
                        disease_stage: "agents/citizens/disease_stage"
                        is_quarantined: "agents/citizens/is_quarantined"
                    output_variables:
                        - quarantine_start_prob
                        - quarantine_break_prob
                        - disease_stage
                        - is_quarantined         
        policy:
            citizens:
                start_compliance:
                    generator: "StartCompliance"
                    arguments: null
                    input_variables: null # from observation (implicit) + state (explicit)
                    output_variables:
                        - start_compliance_action
                break_compliance:
                    generator: "BreakCompliance"
                    arguments: null
                    input_variables: null # from observation (implicit) + state (explicit)
                    output_variables:
                        - break_compliance_action             
        transition:
            update_quarantine_status:
                generator: "UpdateQuarantineStatus"
                arguments: null
                input_variables:
                    is_quarantined: "agents/citizens/is_quarantined"
                    quarantine_start_date: "agents/citizens/quarantine_start_date"
                output_variables:
                    - is_quarantined
                    - quarantine_start_date
    
    "3":
        name: "Testing"
        description: "Conduct test on citizens showing symptoms"
        active_agents:
            - "citizens"
        observation:
            citizens: null
        policy:
            citizens:
                accept_test:
                    generator: "AcceptTest"
                    arguments: null
                    input_variables:
                        disease_stage: "agents/citizens/disease_stage"
                        is_quarantined: "agents/citizens/is_quarantined"
                        test_compliance_prob: "environment/test_compliance_prob"
                    output_variables:
                        - test_acceptance_action
        transition:
            update_test_status:
                generator: "UpdateTestStatus"
                arguments: null
                input_variables:
                    test_true_positive_prob: "environment/test_true_positive_prob"
                    test_false_positive_prob: "environment/test_false_positive_prob"
                    awaiting_test_result: "agents/citizens/awaiting_test_result"
                    disease_stage: "agents/citizens/disease_stage"
                    test_re_eligble_date: "agents/citizens/test_re_eligble_date"
                    test_result_date: "agents/citizens/test_result_date"
                output_variables:
                    - awaiting_test_result
                    - test_result_date
                    - test_re_eligble_date
