simulation_metadata:
    num_episodes: 1
    num_steps_per_episode: 3
    num_substeps_per_step: 0

state:
  environment:
    R:
      name: "R"
      learnable: False
      shape:
          - 1
      initialization_function: null
      value: 5.12
      dtype: "float"
        
    daily_infected:
      name: "daily_infected"
      learnable: False
      shape:
          - ${simulation_metadata.num_steps_per_episode}
      initialization_function: null
      value: 0
      dtype: "float"
  
  agents: null
  objects: null
  network: null

substeps:
    "0":
        name: "Transmission"
        description: "Transmission of new infections"
        active_agents:
            - "citizens"
        observation:
            citizens: null
        policy:
            citizens: null
        transition: null